development_tasks:
  - >
    Create a web page for a device management app. The page should maintain different devices in a web page. 
    The device management app should maintain the following data per device:
    路        Device Name (String)
    路        DeviceType (Allowed types: Smartphone, Tablet, Camera)
    路        Owner Name (String)
    路        Battery Status (0...100%)
    List existing devices of the app in a table.
    Add the possibility to create new devices with a screen to input the data.
    Your solution should be one HTML page with all components, styles and JavaScript code in this file.
  - >
    Add the possibility to update a settings of a selected device in one screen or delete existing devices.
  - >
    When a device was added decrease the per device given Battery Status every second by 1% until it reaches 0%.
    Make sure to update battery status every second in the table.
    Add a colored visualization (e.g. Progress bar) of the battery status to the device table.
  - >
    Use unicode icons for the device types Smartphone, Tablet, Camera.
  - >
    Mark an empty device in red and a device with power in green. Make sure it will stay red when 0% are reached.
  - >
    Provide the possibility to order the device table by Device Name, DeviceType, Owner Name, Battery Status.
  - >
    Add to the existing devices types: Laptop, Car, Powerbank. Provide a matching icon
  - >
    Let a spinner run to visualize that continuous update is working in the background
  - ""

# Future tasks
future_tasks:
  - >
    Store the device settings in the local browser store. Load the devices from the browser store with the page. 
    Make sure it will work when the store is empty and nothing was created (e.g. first start).
